<?php

return [
    [ 'value' => '/sounds/message-pop-alert.mp3', 'label' => 'Message pop alert' ],
    [ 'value' => '/sounds/long-pop.wav', 'label' => 'Long pop alert' ],
    [ 'value' => '/sounds/double-beep-tone.wav', 'label' => 'Double beep tone' ],
    [ 'value' => '/sounds/digital-quick-tone.wav', 'label' => 'Digital quick tone' ],
    [ 'value' => '/sounds/chime-pop.wav', 'label' => 'Fun chime pop' ],
    [ 'value' => 'https://business.waz.com.sa/mnjzChat/sounds/n1.mp3', 'label' => 'notification 1' ],
    [ 'value' => 'https://business.waz.com.sa/mnjzChat/sounds/n2.mp3', 'label' => 'notification 2' ],
    [ 'value' => 'https://business.waz.com.sa/mnjzChat/sounds/n3.mp3', 'label' => 'notification 3' ],
    [ 'value' => 'https://business.waz.com.sa/mnjzChat/sounds/n4.mp3', 'label' => 'notification 4' ],
    [ 'value' => 'https://business.waz.com.sa/mnjzChat/sounds/n5.mp3', 'label' => 'notification 5' ],
    [ 'value' => 'https://business.waz.com.sa/mnjzChat/sounds/n6.mp3', 'label' => 'notification 6' ],
    [ 'value' => 'https://business.waz.com.sa/mnjzChat/sounds/n7.mp3', 'label' => 'notification 7' ],
    [ 'value' => 'https://business.waz.com.sa/mnjzChat/sounds/n8.mp3', 'label' => 'notification 8' ],
    [ 'value' => 'https://business.waz.com.sa/mnjzChat/sounds/9.mp3', 'label' => 'notification 9' ],
    [ 'value' => 'https://business.waz.com.sa/mnjzChat/sounds/10.mp3', 'label' => 'notification 10' ],
    [ 'value' => 'https://business.waz.com.sa/mnjzChat/sounds/11.mp3', 'label' => 'notification 11' ],
    [ 'value' => 'https://business.waz.com.sa/mnjzChat/sounds/12.mp3', 'label' => 'notification 12' ],
    [ 'value' => 'https://business.waz.com.sa/mnjzChat/sounds/13.mp3', 'label' => 'notification 13' ],
    [ 'value' => 'https://business.waz.com.sa/mnjzChat/sounds/14.mp3', 'label' => 'notification 14' ],
    [ 'value' => 'https://business.waz.com.sa/mnjzChat/sounds/15.mp3', 'label' => 'notification 15' ],
    [ 'value' => 'https://business.waz.com.sa/mnjzChat/sounds/16.mp3', 'label' => 'notification 16' ],
    [ 'value' => 'https://business.waz.com.sa/mnjzChat/sounds/17.mp3', 'label' => 'notification 17' ],
    [ 'value' => 'https://business.waz.com.sa/mnjzChat/sounds/18.mp3', 'label' => 'notification 18' ],
];
